# Generated by Django 4.0.4 on 2022-07-04 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('csgoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Players',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('team', models.CharField(max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Tournaments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('region', models.CharField(max_length=40)),
            ],
        ),
    ]
